// <auto-generated />
using System;
using FundosInvestimento.Infra.Data.Contexto;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FundosInvestimento.Infra.Data.Migrations
{
    [DbContext(typeof(FundosInvestimentoContext))]
    [Migration("20190922153504_FundosInvestimento")]
    partial class FundosInvestimento
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FundosInvestimento.Domain.Entities.AplicacaoResgate", b =>
                {
                    b.Property<Guid>("AplicacaoResgateId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("AplicacaoResgateId");

                    b.Property<string>("Cpf")
                        .HasColumnName("Cpf")
                        .HasColumnType("varchar(11)")
                        .HasMaxLength(11);

                    b.Property<DateTime>("DataMovimentacao")
                        .HasColumnName("DataMovimentacao")
                        .HasColumnType("datetime");

                    b.Property<Guid>("FundosId")
                        .HasColumnName("FundosId");

                    b.Property<string>("TipoMovimentacao")
                        .IsRequired()
                        .HasColumnName("TipoMovimentacao")
                        .HasColumnType("varchar(1)");

                    b.Property<decimal>("ValorMovimentacao")
                        .HasColumnName("ValorMovimentacao")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("AplicacaoResgateId")
                        .HasName("AplicacaoResgateId");

                    b.HasIndex("FundosId");

                    b.ToTable("AplicacaoResgate");
                });

            modelBuilder.Entity("FundosInvestimento.Domain.Entities.Fundos", b =>
                {
                    b.Property<Guid>("FundosId")
                        .ValueGeneratedOnAdd()
                        .HasColumnName("FundosId");

                    b.Property<string>("Cnpj")
                        .HasColumnName("Cnpj")
                        .HasColumnType("varchar(14)")
                        .HasMaxLength(14);

                    b.Property<decimal>("InvestimentoInicial")
                        .HasColumnName("InvestimentoInicial")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Nome")
                        .HasColumnName("Nome")
                        .HasColumnType("varchar(150)")
                        .HasMaxLength(150);

                    b.HasKey("FundosId")
                        .HasName("FundosId");

                    b.ToTable("Fundos");
                });

            modelBuilder.Entity("FundosInvestimento.Domain.Entities.AplicacaoResgate", b =>
                {
                    b.HasOne("FundosInvestimento.Domain.Entities.Fundos", "Fundos")
                        .WithMany("AplicacaoResgate")
                        .HasForeignKey("FundosId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
